modkey = Mod4

# --- apps ---
program[term] = xterm
program[menu] = rofi -show drun -theme ~/.local/share/themes/my-theme/rofi/theme.rasi -show-icons
program[fileMgr] = pcmanfm

program[_lock] = ~/bin/lock.sh
program[_powerMenu] = ~/bin/power-menu.sh
program[_screenshot]           = sh -c 'flameshot gui --path ~/Pictures/Screenshots --raw | xclip -selection clipboard -t image/png'
program[_screenshotManual]     = sh -c 'flameshot gui'
program[_screenshotFullscreen] = sh -c 'flameshot full --path ~/Pictures/Screenshots --raw | xclip -selection clipboard -t image/png'
program[_volUp]         = ~/bin/vol-ctl.sh up
program[_volDown]       = ~/bin/vol-ctl.sh down
program[_volMuteToggle] = ~/bin/vol-ctl.sh mute
program[_brightUp]   = ~/bin/brightness-ctl.sh up
program[_brightDown] = ~/bin/brightness-ctl.sh down

# --- autostart ----
autorun = ws[1]:~/bin/set-wallpaper.sh
autorun = ws[1]:dunst
autorun = ws[1]:nm-applet
autorun = ws[1]:tint2
autorun = ws[1]:picom
autorun = ws[1]:xss-lock -- ~/bin/lock.sh

# --- looks ---
border_width = 1

color_focus = rgb:35/7e/c7
color_unfocus = rgb:22/22/22

region_padding = 1
tile_gap = 1

# --- bar ---
bar_enabled = 0
bar_border_width = 0
bar_at_bottom = 1
bar_action_expand = 1
bar_font = sans:size=11

bar_color = rgb:11/11/11
bar_border = rgb:11/11/11
bar_font_color = rgb:ee/ee/ee

bar_format = +|L Workspace: +I +|C %H:%M | %d-%m-%Y +|R +A 
bar_delay = 1
bar_action = ~/bin/spectrwm-status.sh

# --- shorcuts ---
bind[term] = MOD+q
bind[menu] = MOD+d
bind[fileMgr] = MOD+e

bind[wind_del] = MOD+c
bind[float_toggle] = MOD+v
bind[fullscreen_toggle] = MOD+f

bind[_lock] = MOD+Control+l
bind[restart] = MOD+Shift+r
bind[_powerMenu] = MOD+Escape
bind[quit] = MOD+m

bind[focus_prev] = MOD+h
bind[focus_next] = MOD+l

bind[swap_prev] = MOD+Shift+h
bind[swap_next] = MOD+Shift+l

bind[ws_1] = MOD+1
bind[ws_2] = MOD+2
bind[ws_3] = MOD+3
bind[ws_4] = MOD+4
bind[ws_5] = MOD+5
bind[ws_6] = MOD+6
bind[ws_7] = MOD+7
bind[ws_8] = MOD+8
bind[ws_9] = MOD+9
bind[ws_10] = MOD+0

bind[mvws_1] = MOD+Shift+1
bind[mvws_2] = MOD+Shift+2
bind[mvws_3] = MOD+Shift+3
bind[mvws_4] = MOD+Shift+4
bind[mvws_5] = MOD+Shift+5
bind[mvws_6] = MOD+Shift+6
bind[mvws_7] = MOD+Shift+7
bind[mvws_8] = MOD+Shift+8
bind[mvws_9] = MOD+Shift+9
bind[mvws_10] = MOD+Shift+0

bind[_screenshot]           = Print
bind[_screenshotManual]     = Shift+Print
bind[_screenshotFullscreen] = Control+Print

bind[_volUp]         = XF86AudioRaiseVolume
bind[_volDown]       = XF86AudioLowerVolume
bind[_volMuteToggle] = XF86AudioMute

bind[_brightUp]   = XF86MonBrightnessUp
bind[_brightDown] = XF86MonBrightnessDown
